export const ADD_ALL_CATEGORIES = 'ADD_ALL_CATEGORIES';

export const ADD_ALL_POSTS = 'ADD_ALL_POSTS';

export const API_FAIL = 'API_FAIL';

export const API_IDLE = 'API_IDLE';

export const API_LOADING = 'API_LOADING';

export const API_SUCCESS = 'API_SUCCESS';

export const CHANGE_ORDER_ALL_POSTS = 'CHANGE_ORDER_ALL_POSTS';

export const CHANGE_STATUS_CATEGORY_GET_ALL = 'CHANGE_STATUS_CATEGORY_GET_ALL';

export const CHANGE_STATUS_POST_GET_ALL = 'CHANGE_STATUS_POST_GET_ALL';

export const CHANGE_STATUS_POST_SAVE = 'CHANGE_STATUS_POST_SAVE';

export const VOTE_POST = 'VOTE_POST';